### ISSUE TITLE
Spike: Revisit the issue of adding rate limiting logic to the application, create a list of actionable issues to start the effort.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse-pm#23]
This ticket is a placeholder for general API rate and access limiting logic to better control the load placed on the service and provide options in case of system instability.

Rate limiting was mentioned during search api testing and github search api uses this concept too:
https://developer.github.com/v3/search/

Limiting access might involve varying degrees of options: general api access on/off switch, per api, and/or whitelist/blacklist of ip addresses/ users. The last might be integrated with groups and permissions. 

---

Update: additional terms for this:

- API throttling

**Comment by mreekie** [comment]
grooming:
- This needs to be looked at again.
- For now I put it in the backlog and added the deliverable label.

**Comment by scolapasta** [comment]
Closing this, now that we have https://github.com/IQSS/dataverse/pull/10211 in progress.

**Comment by landreev** [comment]
@scolapasta Are you sure you wanted to close this one? 
Note that this spike was for being able to limit *everything* across the application; with the idea, I think, that more than one solution may be need in parallel, for different parts of the application.
IQSS/dataverse#10211, and the corresponding issue are specifically for the Command Engine only.

I can see how an argument can be made that if there is anything potentially expensive that we want to ration, that's done bypassing the command system, then it could potentially be addressed by creating dedicated commands for all such things... But I still think that would need to be discussed to make sure we're not missing anything.

**Comment by scolapasta** [comment]
@landreev If there are other areas that we do need to ration, outside of the command system, then I'd vote for creating more specific actionable issues for it. This one here was in the dm-project and I do think we've made plenty of headway on different aspects and I think that accomplished the goal of "creat[ing] a list of actionable issues to start the effort".  But if you feel otherwise and think there's something more we can do for this one specifically, that's fine too.
