### ISSUE TITLE
Retrospective: 3/30/23 Start doing a briefing on where the project is at as a whole, once a month.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse-pm#34]
From: https://docs.google.com/document/d/12lTHcWq7kl8eNITFNCehIFG-EsjxBPA_v70XIW6DLEE/edit?usp=sharing

(KC) Start doing a briefing on where the project is at as a whole, maybe after standup, perhaps once a month? (KC)(+1 SEK) (+1EK)

Note: Mike pointed out that the monthly lunch meetings are supposed to provide this info but more recently they have either featured a speaker or people were away so that recap/summary didn't take place. Maybe trying to always include it as a part, even just 10 mins?

**Comment by kcondon** [comment]
What I would like to see: A summary of what was done in the past month relative to road map/strategy, what will be done next month relative roadmap/strategy, other activities/initiatives of note, nice to have: volume of work completed by the team.

**Comment by pdurbin** [comment]
@cmbz asked us to comment on this issue with what we want. Or at least to give some perspective? Something like that! 😅 

As I said during the retrospective, this issue is framed around the past (a recap) but I'm also interested in the future (a roadmap) so I'll cover both.

As someone close to the code, I don't particularly need someone to tell me which pull requests have been merged and therefore what will be in the next release. During community calls I try to summarize this information for attendees (and Jim does a great job of covering code he's written for GDCC).

I would appreciate a recap of meetings on budding partnerships, grant proposals, conferences attended, trip reports, and new projects on the horizon. This sort of chatter is off topic for daily standups and really any [regular meeting we have.](https://github.com/IQSS/dataverse-pm-transition/issues/4)

I'm open to having the recap monthly, bimonthly, or quarterly, whatever makes sense. As I said during the retro, the entire community can at least be assured that they'll get a recap once a year at the community meeting.

Since late 2016, I've written 78 monthly "Dataverse Community News" newsletters trying to recap what's going on: https://groups.google.com/g/dataverse-community?label=community_news . I hope it helps but I have the feeling that there's a lot more going on that I don't even know about.

As for the future, I've had a hand in removing extremely out of date content from https://www.iq.harvard.edu/roadmap-dataverse-project but I don't feel empowered or informed enough to know what to even write there. Roadmaps are important. We should update that page. We should talk about it with the community. Currently there's nothing to talk about because that page never changes. (During commuity meetings I do sometimes bring up stuff that's very much going on but that isn't on the roadmap page such as development of the new fronted.) Again, the annual community meeting is a time when information is communicated, but a year is a long time to wait!

We do an ok job of communicating what will be worked on in the next couple weeks. No complaints there.

I feel like I'd have a better sense of both the past and the future if I were invited to the weekly prioritization meeting. To me, this is the inner circle of Dataverse.

**Comment by kcondon** [comment]
The idea I had for this issue was to improve the sense of cohesion for the team around the work each of us does and the various activities we hear about and how they support the team's strategic goals and mission. As pointed out, there are lots of communication channels, serving different purposes and audiences. That is a broad topic and offers many topics for retro. I was hoping this issue would address the local team's need to stay informed, stay connected with leadership, gain important context, and not have to develop this information on our own or chase down sources.

**Comment by cmbz** [comment]
I am assigning myself this issue and mulling on ideas for addressing the different needs described in the two comments above.

In the meantime, Stefano will provide an update about partnerships and related project activities at the 3 May Dataverse Project Monthly Meeting (our belated April meeting).

Another project meeting is scheduled for 24 May, too. I'll reach out to everyone then about including additional relevant updates to the agenda.

**Comment by cmbz** [comment]
Closing old, stale issues.
