### ISSUE TITLE
PPR - Dev. Email redirection.

### ISSUE THREAD

**Issue by jp-tosca** [IQSS/dataverse-pm#350]
It was requested to look into https://github.com/IQSS/ppr-pm/issues/10 for https://github.com/IQSS/ppr-ojs we will reach out to Aday and research and size this.

**Comment by rnichols7** [comment]
@cmbz or @jp-tosca, do I need to submit a ticket to PKP, or am I waiting for you to figure out the configuration on your end?

**Comment by jp-tosca** [comment]
@rnichols7 let's follow up with PKP as we mentioned, it seems that they will know if anything has to be done on our side.

It seems per Aday's email that no development tasks will be required.

**Comment by rnichols7** [comment]
Hello JP,

Thanks for your response.

I spoke to Aday today, and this is a three-step process with a configuration in the mix.

Step 1: The first step is to contact HUIT to update the DNS records for iq.harvard.edu<http://iq.harvard.edu> to add the PKP OJS server IP address to the SPF record.

  *   This was done for the current domain: pre-review.iq.havard.edu<https://urldefense.proofpoint.com/v2/url?u=http-3A__pre-2Dreview.iq.havard.edu&d=DwMFaQ&c=WO-RGvefibhHBZq3fL85hQ&r=3qSQ3FGBC1l0HAB83a6_d4b3LEzFRGcmsQgFO1b5jGE&m=4t1w0Bdk9qKq52W4-liAHEGUoQFPcnr1M_5bOXvaI-ObBivUU-h3S5maDJd5-hTL&s=hbdnDwQxHCI0xhcdDWQwhAJAQnZt3yeg69yMrTJQU9c&e=>.
  *   We need to engage with the team that manages the iq.havard.edu<https://urldefense.proofpoint.com/v2/url?u=http-3A__iq.havard.edu&d=DwMFaQ&c=WO-RGvefibhHBZq3fL85hQ&r=3qSQ3FGBC1l0HAB83a6_d4b3LEzFRGcmsQgFO1b5jGE&m=4t1w0Bdk9qKq52W4-liAHEGUoQFPcnr1M_5bOXvaI-ObBivUU-h3S5maDJd5-hTL&s=GPMTGbtFq31KOldACVi3KH2_xFaPbxSlJSoSPU7_NGQ&e=> domain to implement these changes.
  *   More info from PKP on email configuration: https://docs.pkp.sfu.ca/admin-guide/3.3/en/email#spf-and-dmarc-issues<https://urldefense.proofpoint.com/v2/url?u=https-3A__docs.pkp.sfu.ca_admin-2Dguide_3.3_en_email-23spf-2Dand-2Ddmarc-2Dissues&d=DwMFaQ&c=WO-RGvefibhHBZq3fL85hQ&r=3qSQ3FGBC1l0HAB83a6_d4b3LEzFRGcmsQgFO1b5jGE&m=4t1w0Bdk9qKq52W4-liAHEGUoQFPcnr1M_5bOXvaI-ObBivUU-h3S5maDJd5-hTL&s=B4dRT3RYde2m21iMG-KZCRtbqSrI65kQ6GGK6g6mNec&e=>
Step 2: After the DNS has been updated, we need to open a ticket with PKP to request that they update the email address in the OJS configuration.

  *   I need all reply emails sent to ***@***.******@***.***> instead of the original sender.

Step 3: OJS customization to override the reply-to address that OJS sets in outgoing emails.


From: Juan Pablo Tosca Villanueva ***@***.***>
Reply-To: IQSS/dataverse-pm ***@***.***>
Date: Tuesday, December 10, 2024 at 2:21 PM
To: IQSS/dataverse-pm ***@***.***>
Cc: Rebecca Nichols ***@***.***>, Mention ***@***.***>
Subject: Re: [IQSS/dataverse-pm] PPR - Dev. Email redirection. (Issue #350)


@rnichols7<https://github.com/rnichols7> let's follow up with PKP as we mentioned, it seems that they will know if anything has to be done on our side.

It seems per Aday's email that no development tasks will be required.
