### ISSUE TITLE
Retrospective: 4-12-23 Start Communicating which conference people are going to

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse-pm#67]
Start:
(PD) Communicating which conference people are going to (KC, PD)

From: https://docs.google.com/document/d/1TVS7eJo5koPbK39QP_0N8IPk_Wp6JQSvCaMQl0LLBBI/edit

**Comment by cmbz** [comment]
Here are some options:

1. Share our conference/workshop/activity updates during each Dataverse Project Monthly Meeting, as shown on [this slide in our meeting slide deck](https://docs.google.com/presentation/d/19tjk8aet-qPu8UVdLsI38NoInm5yZx5PCvZzPJiG300/edit?usp=sharing).
2. Update a dedicated spreadsheet with this information on a regular basis.

Thoughts on these, or other approaches?

**Comment by pdurbin** [comment]
@cmbz we have a internal spreadsheet at https://docs.google.com/spreadsheets/d/1x6vUheVO7bNWb7_h36AGtlGWm4BofXhskblVVhcji0w/edit?usp=sharing

It seems to be working pretty well. 😄

**Comment by cmbz** [comment]
@pdurbin @kcondon Since the spreadsheet already exists, what if I add a tab for next fiscal year for folks to add the conferences they'd like to attend?

**Comment by pdurbin** [comment]
@cmbz sounds fine to me.

Also, there's a public spreadsheet as well. It lost steam because of the pandemic but the idea was that people around the world attending conferences that are adjacent to Dataverse could find each other and maybe even have a little Dataverse meetup on the side (or at least grab a coffee together): https://groups.google.com/g/dataverse-community/c/Jk10Z5QCrmo/m/Pt6LoiJFBgAJ
